// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjD6ICGEugChS4IO-guj-N3SE7mhWrIo',
    appId: '1:369550718965:web:31521d30bb9be4bdccd2bc',
    messagingSenderId: '369550718965',
    projectId: 'servicly-92872',
    authDomain: 'servicly-92872.firebaseapp.com',
    storageBucket: 'servicly-92872.firebasestorage.app',
    measurementId: 'G-NNSWDZXJNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6zEqHmbwadWACblR85TejV-y0PMCIzE',
    appId: '1:369550718965:android:4aa1b431ad6a773bccd2bc',
    messagingSenderId: '369550718965',
    projectId: 'servicly-92872',
    storageBucket: 'servicly-92872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ITR9vKni1C185K5KOv2KAs89KF-Ftzs',
    appId: '1:369550718965:ios:d346c12738822a94ccd2bc',
    messagingSenderId: '369550718965',
    projectId: 'servicly-92872',
    storageBucket: 'servicly-92872.firebasestorage.app',
    iosClientId: '369550718965-8hh0b42945sicl421fvesmv5a6ehh8mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.proveedorServiclyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ITR9vKni1C185K5KOv2KAs89KF-Ftzs',
    appId: '1:369550718965:ios:d346c12738822a94ccd2bc',
    messagingSenderId: '369550718965',
    projectId: 'servicly-92872',
    storageBucket: 'servicly-92872.firebasestorage.app',
    iosClientId: '369550718965-8hh0b42945sicl421fvesmv5a6ehh8mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.proveedorServiclyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcjD6ICGEugChS4IO-guj-N3SE7mhWrIo',
    appId: '1:369550718965:web:a6836ec672e3fb74ccd2bc',
    messagingSenderId: '369550718965',
    projectId: 'servicly-92872',
    authDomain: 'servicly-92872.firebaseapp.com',
    storageBucket: 'servicly-92872.firebasestorage.app',
    measurementId: 'G-K5E55HXJGL',
  );

}