// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJg0bs0TFtXyKfSITFXKui06zW8PtTs94',
    appId: '1:1002089002297:web:3ee701e580cb2349a2a4e8',
    messagingSenderId: '1002089002297',
    projectId: 'servicly-app-mobile',
    authDomain: 'servicly-app-mobile.firebaseapp.com',
    storageBucket: 'servicly-app-mobile.firebasestorage.app',
    measurementId: 'G-302LFSLNK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9Jv7n8J_fN617dbFmDJQYtIl4OigKlg',
    appId: '1:1002089002297:android:3f3c329e10b2d541a2a4e8',
    messagingSenderId: '1002089002297',
    projectId: 'servicly-app-mobile',
    storageBucket: 'servicly-app-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2BRos6Na05qspoQdQzziczg487-lCeHw',
    appId: '1:1002089002297:ios:3b7871d53afcf194a2a4e8',
    messagingSenderId: '1002089002297',
    projectId: 'servicly-app-mobile',
    storageBucket: 'servicly-app-mobile.firebasestorage.app',
    iosBundleId: 'com.example.proveedorServiclyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2BRos6Na05qspoQdQzziczg487-lCeHw',
    appId: '1:1002089002297:ios:3b7871d53afcf194a2a4e8',
    messagingSenderId: '1002089002297',
    projectId: 'servicly-app-mobile',
    storageBucket: 'servicly-app-mobile.firebasestorage.app',
    iosBundleId: 'com.example.proveedorServiclyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJg0bs0TFtXyKfSITFXKui06zW8PtTs94',
    appId: '1:1002089002297:web:cd5a3a37eaa66d0ea2a4e8',
    messagingSenderId: '1002089002297',
    projectId: 'servicly-app-mobile',
    authDomain: 'servicly-app-mobile.firebaseapp.com',
    storageBucket: 'servicly-app-mobile.firebasestorage.app',
    measurementId: 'G-WE5KK6GVBJ',
  );
}
